spring.application.name=atizay

# ======================
# DATABASE (POSTGRES RENDER)
# ======================
spring.datasource.url=jdbc:postgresql://dpg-d7mcjkpo3t8c73e3no3g-a.oregon-postgres.render.com:5432/atizay_bd
spring.datasource.username=atizay_bd_user
spring.datasource.password=mKg656SlyuhhuZETsd9yIZwfGpVakdg4
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ======================
# SERVER (IMPORTANT POUR RENDER)
# ======================
server.port=${PORT:8080}

# ======================
# LOGS (optionnel)
# ======================
logging.level.root=INFO

# ======================
# DESACTIVER OAUTH2 (IMPORTANT)
# ======================
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=

spring.security.oauth2.client.registration.facebook.client-id=
spring.security.oauth2.client.registration.facebook.client-secret=

# ======================
# DESACTIVER MONCASH TEMPORAIRE
# ======================
moncash.client.id=dummy
moncash.client.secret=dummy

# ======================
# ADMIN
# ======================
admin.email=admin@atizay.com
admin.password=Admin123!