spring.application.name=atizay

# PostgreSQL Render
spring.datasource.url=jdbc:postgresql://dpg-d7mcjkpo3t8c73e3no3g-a.oregon-postgres.render.com:5432/atizay_bd
spring.datasource.username=atizay_bd_user
spring.datasource.password=mKg656SlyuhhuZETsd9yIZwfGpVakdg4
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8081}

# 🚫 Désactiver OAuth COMPLET
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration

# MonCash temporaire
moncash.client.id=TEST
moncash.client.secret=TEST

# Admin
admin.email=admin@atizay.com
admin.password=Admin123!