spring.application.name=atizay
spring.datasource.url=jdbc:mysql://localhost:3306/atizay?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=@msterlyCA002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.ht.amsterly.atizay=DEBUG
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
server.port=8080
spring.security.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=5000MB

# --- CONFIGURATION OAUTH2 (GOOGLE & FACEBOOK) ---
# Vous devez remplir ces informations pour activer la connexion sociale

# Google
spring.security.oauth2.client.registration.google.client-id=VOTRE_CLIENT_ID_GOOGLE.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=VOTRE_CLIENT_SECRET_GOOGLE
spring.security.oauth2.client.registration.google.scope=profile,email

# Facebook
spring.security.oauth2.client.registration.facebook.client-id=VOTRE_APP_ID_FACEBOOK
spring.security.oauth2.client.registration.facebook.client-secret=VOTRE_APP_SECRET_FACEBOOK
spring.security.oauth2.client.registration.facebook.scope=public_profile,email